[package]
name = "mktemp"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mktemp"
path = "mktemp.rs"

[dependencies]
uucore = { path="../uucore" }
getopts = "0.2.14"
rand = "0.4"
tempfile = "3.0.2"

[[bin]]
name = "mktemp"
path = "../../uumain.rs"
